<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PABC.MigrationService-12dc61df-1c53-4863-a76e-305b59ae3b84</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Corvus.Text.Json" />
    <PackageReference Include="Corvus.Text.Json.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="dataset.schema.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PABC.Data\PABC.Data.csproj" />
    <ProjectReference Include="..\PABC.ServiceDefaults\PABC.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>