apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pabc.fullname" . }}
  labels:
    {{- include "pabc.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ .Values.global.settings.databaseHost | default .Values.settings.database.host | toString | quote }}
  POSTGRES_DB: {{ .Values.settings.database.name | toString | quote }}
  POSTGRES_PORT: {{ .Values.settings.database.port | toString | quote }}
  POSTGRES_USER: {{ .Values.settings.database.username | toString | quote }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: {{ .Values.settings.aspnetcore.forwardedHeadersEnabled | toString | quote }}
  {{- if .Values.settings.aspnetcore.environment }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.settings.aspnetcore.environment | toString | quote }}
  {{- end }}
  {{- if .Values.settings.aspnetcore.httpPorts }}
  ASPNETCORE_HTTP_PORTS: {{ .Values.settings.aspnetcore.httpPorts | toString | quote }}
  {{- end }}