apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pabc.fullname" . }}
  labels:
    {{- include "pabc.labels" . | nindent 4 }}
data:
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: {{ .Values.settings.aspnetcore.forwardedHeadersEnabled | toString | quote }}
  {{- if .Values.settings.aspnetcore.environment }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.settings.aspnetcore.environment | toString | quote }}
  {{- end }}
  {{- if .Values.settings.aspnetcore.httpPorts }}
  ASPNETCORE_HTTP_PORTS: {{ .Values.settings.aspnetcore.httpPorts | toString | quote }}
  {{- end }}
  {{- if .Values.migrations.dataSetPath }}
  JSON_DATASET_PATH: {{ .Values.migrations.dataSetPath | toString | quote }}
  {{- end }}
  {{- if .Values.settings.oidc.authority }}
  Oidc__Authority: {{ .Values.settings.oidc.authority }}
  Oidc__ClientId: {{ .Values.settings.oidc.clientId }}
  Oidc__FunctioneelBeheerderRole: {{ .Values.settings.oidc.functioneelBeheerderRole }}
  Oidc__NameClaimType: {{ .Values.settings.oidc.nameClaimType }}
  Oidc__RoleClaimType: {{ .Values.settings.oidc.roleClaimType }}
  Oidc__EmailClaimType: {{ .Values.settings.oidc.emailClaimType }}
  {{- end }}