{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pabc.fullname" . }}
  labels:
    {{- include "pabc.labels" . | nindent 4 }}
type: Opaque
data:
  ConnectionStrings__Pabc: {{ include "pabc.databaseConnectionString" . | b64enc }}
  {{- range $index, $apiKey := $.Values.settings.apiKeys }}
  API_KEY__{{ $index }}: {{ $apiKey | b64enc }}
  {{- end }}   
{{- end }}
