kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "pabc.fullname" . }}-service-job-reader
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]