@PABC.Server_HostAddress = http://localhost:5211


POST {{PABC.Server_HostAddress}}/api/v1/application-roles-per-entity-type/
X-API-KEY: unsafe-test-api-key
Content-Type: application/json
{
  "FunctionalRoleNames": ["GemeenteRol1", "GemeenteRol2"]
}


###


GET {{PABC.Server_HostAddress}}/api/v1/seed
X-API-KEY: unsafe-test-api-key