name: Generate and Commit Swagger YAML
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'PABC.Server/PABC.Server.json'
  pull_request:
    paths-ignore:
      - 'PABC.Server/PABC.Server.json'
  workflow_dispatch:

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore PABC.sln

    - name: Build PABC.Server
      run: dotnet build PABC.Server/PABC.Server.csproj --no-restore --configuration Release

    - name: Check for changes in PABC.Server.json
      id: check-changes
      run: |
        if git diff --quiet PABC.Server/PABC.Server.json; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add PABC.Server/PABC.Server.json
        git commit -m "Update OpenAPI documentation [skip ci]"
        git push 